### ISSUE TITLE
Error when opening up: unexpected token s

### ISSUE THREAD

**Issue by hazcod** [t411flix/t411flix#1]
```
Server listening on port 3000
GET / 302 18.799 ms - 60
undefined:1
string(5) "1.2.4"
^

SyntaxError: Unexpected token s
    at Object.parse (native)
    at /home/niels/Downloads/t411flix-master/node_modules/t411/index.js:192:21
    at Request.callback (/home/niels/Downloads/t411flix-master/node_modules/t411/node_modules/superagent/lib/node/index.js:785:12)
    at Stream.<anonymous> (/home/niels/Downloads/t411flix-master/node_modules/t411/node_modules/superagent/lib/node/index.js:990:12)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at Unzip.<anonymous> (/home/niels/Downloads/t411flix-master/node_modules/t411/node_modules/superagent/lib/node/utils.js:108:12)
    at emitNone (events.js:72:20)
    at Unzip.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
```

node 5.0.0

**Comment by hazcod** [comment]
Fixed after changing api url to .in
Please modify this in your npm package 't411'
